/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResourceId = IDL.Nat;
export const FileType = IDL.Variant({ 'pdf' : IDL.Null, 'link' : IDL.Null });
export const Resource = IDL.Record({
  'id' : ResourceId,
  'url' : IDL.Text,
  'title' : IDL.Text,
  'semester' : IDL.Nat,
  'subjectCode' : IDL.Text,
  'fileType' : FileType,
  'uploader' : IDL.Principal,
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SessionId = IDL.Nat;
export const BookingStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const SessionBooking = IDL.Record({
  'id' : SessionId,
  'status' : BookingStatus,
  'junior' : IDL.Principal,
  'subjectCode' : IDL.Text,
  'senior' : IDL.Principal,
  'price' : IDL.Nat,
  'dateTime' : Time,
});
export const TutorProfile = IDL.Record({
  'user' : IDL.Principal,
  'isAvailable' : IDL.Bool,
  'isVerified' : IDL.Bool,
  'avatarUrl' : IDL.Text,
  'rating' : IDL.Opt(IDL.Float64),
  'masteredSubjects' : IDL.Vec(IDL.Text),
});
export const UserRole = IDL.Variant({
  'junior' : IDL.Null,
  'senior' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'branch' : IDL.Text,
  'semester' : IDL.Nat,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
  'university' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addResource' : IDL.Func([Resource], [ResourceId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'bookSession' : IDL.Func([SessionBooking], [SessionId], []),
  'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
  'getAvailableTutors' : IDL.Func([], [IDL.Vec(TutorProfile)], ['query']),
  'getBookingsByStatus' : IDL.Func(
      [BookingStatus],
      [IDL.Vec(SessionBooking)],
      ['query'],
    ),
  'getCallerSessions' : IDL.Func([], [IDL.Vec(SessionBooking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getResourcesBySemester' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(Resource)],
      ['query'],
    ),
  'getResourcesBySemesterAndSubject' : IDL.Func(
      [IDL.Nat, IDL.Text],
      [IDL.Vec(Resource)],
      ['query'],
    ),
  'getResourcesBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Resource)],
      ['query'],
    ),
  'getSessionsForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(SessionBooking)],
      ['query'],
    ),
  'getTutorProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TutorProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerifiedTutors' : IDL.Func([], [IDL.Vec(TutorProfile)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTutorsBySubject' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TutorProfile)],
      ['query'],
    ),
  'updateSessionStatus' : IDL.Func([SessionId, BookingStatus], [], []),
  'updateTutorAvailability' : IDL.Func([IDL.Bool], [], []),
  'updateTutorSubjects' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'verifyTutor' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResourceId = IDL.Nat;
  const FileType = IDL.Variant({ 'pdf' : IDL.Null, 'link' : IDL.Null });
  const Resource = IDL.Record({
    'id' : ResourceId,
    'url' : IDL.Text,
    'title' : IDL.Text,
    'semester' : IDL.Nat,
    'subjectCode' : IDL.Text,
    'fileType' : FileType,
    'uploader' : IDL.Principal,
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SessionId = IDL.Nat;
  const BookingStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const SessionBooking = IDL.Record({
    'id' : SessionId,
    'status' : BookingStatus,
    'junior' : IDL.Principal,
    'subjectCode' : IDL.Text,
    'senior' : IDL.Principal,
    'price' : IDL.Nat,
    'dateTime' : Time,
  });
  const TutorProfile = IDL.Record({
    'user' : IDL.Principal,
    'isAvailable' : IDL.Bool,
    'isVerified' : IDL.Bool,
    'avatarUrl' : IDL.Text,
    'rating' : IDL.Opt(IDL.Float64),
    'masteredSubjects' : IDL.Vec(IDL.Text),
  });
  const UserRole = IDL.Variant({ 'junior' : IDL.Null, 'senior' : IDL.Null });
  const UserProfile = IDL.Record({
    'branch' : IDL.Text,
    'semester' : IDL.Nat,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
    'university' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addResource' : IDL.Func([Resource], [ResourceId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'bookSession' : IDL.Func([SessionBooking], [SessionId], []),
    'getAllResources' : IDL.Func([], [IDL.Vec(Resource)], ['query']),
    'getAvailableTutors' : IDL.Func([], [IDL.Vec(TutorProfile)], ['query']),
    'getBookingsByStatus' : IDL.Func(
        [BookingStatus],
        [IDL.Vec(SessionBooking)],
        ['query'],
      ),
    'getCallerSessions' : IDL.Func([], [IDL.Vec(SessionBooking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getResourcesBySemester' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'getResourcesBySemesterAndSubject' : IDL.Func(
        [IDL.Nat, IDL.Text],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'getResourcesBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Resource)],
        ['query'],
      ),
    'getSessionsForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(SessionBooking)],
        ['query'],
      ),
    'getTutorProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TutorProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerifiedTutors' : IDL.Func([], [IDL.Vec(TutorProfile)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTutorsBySubject' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TutorProfile)],
        ['query'],
      ),
    'updateSessionStatus' : IDL.Func([SessionId, BookingStatus], [], []),
    'updateTutorAvailability' : IDL.Func([IDL.Bool], [], []),
    'updateTutorSubjects' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'verifyTutor' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };