/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BookingStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type FileType = { 'pdf' : null } |
  { 'link' : null };
export interface Resource {
  'id' : ResourceId,
  'url' : string,
  'title' : string,
  'semester' : bigint,
  'subjectCode' : string,
  'fileType' : FileType,
  'uploader' : Principal,
}
export type ResourceId = bigint;
export interface SessionBooking {
  'id' : SessionId,
  'status' : BookingStatus,
  'junior' : Principal,
  'subjectCode' : string,
  'senior' : Principal,
  'price' : bigint,
  'dateTime' : Time,
}
export type SessionId = bigint;
export type Time = bigint;
export interface TutorProfile {
  'user' : Principal,
  'isAvailable' : boolean,
  'isVerified' : boolean,
  'avatarUrl' : string,
  'rating' : [] | [number],
  'masteredSubjects' : Array<string>,
}
export interface UserProfile {
  'branch' : string,
  'semester' : bigint,
  'name' : string,
  'role' : UserRole,
  'email' : string,
  'university' : string,
}
export type UserRole = { 'junior' : null } |
  { 'senior' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addResource' : ActorMethod<[Resource], ResourceId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'bookSession' : ActorMethod<[SessionBooking], SessionId>,
  'getAllResources' : ActorMethod<[], Array<Resource>>,
  'getAvailableTutors' : ActorMethod<[], Array<TutorProfile>>,
  'getBookingsByStatus' : ActorMethod<[BookingStatus], Array<SessionBooking>>,
  'getCallerSessions' : ActorMethod<[], Array<SessionBooking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getResourcesBySemester' : ActorMethod<[bigint], Array<Resource>>,
  'getResourcesBySemesterAndSubject' : ActorMethod<
    [bigint, string],
    Array<Resource>
  >,
  'getResourcesBySubject' : ActorMethod<[string], Array<Resource>>,
  'getSessionsForUser' : ActorMethod<[Principal], Array<SessionBooking>>,
  'getTutorProfile' : ActorMethod<[Principal], [] | [TutorProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerifiedTutors' : ActorMethod<[], Array<TutorProfile>>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'registerCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchTutorsBySubject' : ActorMethod<[string], Array<TutorProfile>>,
  'updateSessionStatus' : ActorMethod<[SessionId, BookingStatus], undefined>,
  'updateTutorAvailability' : ActorMethod<[boolean], undefined>,
  'updateTutorSubjects' : ActorMethod<[Array<string>], undefined>,
  'verifyTutor' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];