/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface TutorProfile {
    user: Principal;
    isAvailable: boolean;
    isVerified: boolean;
    avatarUrl: string;
    rating?: number;
    masteredSubjects: Array<string>;
}
export type SessionId = bigint;
export interface Resource {
    id: ResourceId;
    url: string;
    title: string;
    semester: bigint;
    subjectCode: string;
    fileType: FileType;
    uploader: Principal;
}
export type ResourceId = bigint;
export interface SessionBooking {
    id: SessionId;
    status: BookingStatus;
    junior: Principal;
    subjectCode: string;
    senior: Principal;
    price: bigint;
    dateTime: Time;
}
export interface UserProfile {
    branch: string;
    semester: bigint;
    name: string;
    role: UserRole;
    email: string;
    university: string;
}
export enum BookingStatus {
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum FileType {
    pdf = "pdf",
    link = "link"
}
export enum UserRole {
    junior = "junior",
    senior = "senior"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addResource(resource: Resource): Promise<ResourceId>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    bookSession(booking: SessionBooking): Promise<SessionId>;
    getAllResources(): Promise<Array<Resource>>;
    getAvailableTutors(): Promise<Array<TutorProfile>>;
    getBookingsByStatus(status: BookingStatus): Promise<Array<SessionBooking>>;
    getCallerSessions(): Promise<Array<SessionBooking>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getResourcesBySemester(semester: bigint): Promise<Array<Resource>>;
    getResourcesBySemesterAndSubject(semester: bigint, subjectCode: string): Promise<Array<Resource>>;
    getResourcesBySubject(subjectCode: string): Promise<Array<Resource>>;
    getSessionsForUser(user: Principal): Promise<Array<SessionBooking>>;
    getTutorProfile(user: Principal): Promise<TutorProfile | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVerifiedTutors(): Promise<Array<TutorProfile>>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    registerCallerUserProfile(userProfile: UserProfile): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchTutorsBySubject(subjectCode: string): Promise<Array<TutorProfile>>;
    updateSessionStatus(bookingId: SessionId, status: BookingStatus): Promise<void>;
    updateTutorAvailability(isAvailable: boolean): Promise<void>;
    updateTutorSubjects(subjects: Array<string>): Promise<void>;
    verifyTutor(user: Principal): Promise<void>;
}
import type { BookingStatus as _BookingStatus, FileType as _FileType, Resource as _Resource, ResourceId as _ResourceId, SessionBooking as _SessionBooking, SessionId as _SessionId, Time as _Time, TutorProfile as _TutorProfile, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addResource(arg0: Resource): Promise<ResourceId> {
        if (this.processError) {
            try {
                const result = await this.actor.addResource(to_candid_Resource_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addResource(to_candid_Resource_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookSession(arg0: SessionBooking): Promise<SessionId> {
        if (this.processError) {
            try {
                const result = await this.actor.bookSession(to_candid_SessionBooking_n7(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookSession(to_candid_SessionBooking_n7(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllResources(): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllResources();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllResources();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAvailableTutors(): Promise<Array<TutorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAvailableTutors();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAvailableTutors();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingsByStatus(arg0: BookingStatus): Promise<Array<SessionBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByStatus(to_candid_BookingStatus_n9(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByStatus(to_candid_BookingStatus_n9(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerSessions(): Promise<Array<SessionBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerSessions();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerSessions();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResourcesBySemester(arg0: bigint): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesBySemester(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesBySemester(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResourcesBySemesterAndSubject(arg0: bigint, arg1: string): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesBySemesterAndSubject(arg0, arg1);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesBySemesterAndSubject(arg0, arg1);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResourcesBySubject(arg0: string): Promise<Array<Resource>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResourcesBySubject(arg0);
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResourcesBySubject(arg0);
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSessionsForUser(arg0: Principal): Promise<Array<SessionBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSessionsForUser(arg0);
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSessionsForUser(arg0);
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTutorProfile(arg0: Principal): Promise<TutorProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTutorProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTutorProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerifiedTutors(): Promise<Array<TutorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerifiedTutors();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerifiedTutors();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async registerCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n33(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchTutorsBySubject(arg0: string): Promise<Array<TutorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTutorsBySubject(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTutorsBySubject(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateSessionStatus(arg0: SessionId, arg1: BookingStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSessionStatus(arg0, to_candid_BookingStatus_n9(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSessionStatus(arg0, to_candid_BookingStatus_n9(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateTutorAvailability(arg0: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTutorAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTutorAvailability(arg0);
            return result;
        }
    }
    async updateTutorSubjects(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTutorSubjects(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTutorSubjects(arg0);
            return result;
        }
    }
    async verifyTutor(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyTutor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyTutor(arg0);
            return result;
        }
    }
}
function from_candid_BookingStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_FileType_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileType): FileType {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Resource_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Resource): Resource {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_SessionBooking_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SessionBooking): SessionBooking {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_TutorProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TutorProfile): TutorProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n26(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TutorProfile]): TutorProfile | null {
    return value.length === 0 ? null : from_candid_TutorProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ResourceId;
    url: string;
    title: string;
    semester: bigint;
    subjectCode: string;
    fileType: _FileType;
    uploader: Principal;
}): {
    id: ResourceId;
    url: string;
    title: string;
    semester: bigint;
    subjectCode: string;
    fileType: FileType;
    uploader: Principal;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        semester: value.semester,
        subjectCode: value.subjectCode,
        fileType: from_candid_FileType_n14(_uploadFile, _downloadFile, value.fileType),
        uploader: value.uploader
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    user: Principal;
    isAvailable: boolean;
    isVerified: boolean;
    avatarUrl: string;
    rating: [] | [number];
    masteredSubjects: Array<string>;
}): {
    user: Principal;
    isAvailable: boolean;
    isVerified: boolean;
    avatarUrl: string;
    rating?: number;
    masteredSubjects: Array<string>;
} {
    return {
        user: value.user,
        isAvailable: value.isAvailable,
        isVerified: value.isVerified,
        avatarUrl: value.avatarUrl,
        rating: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.rating)),
        masteredSubjects: value.masteredSubjects
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _SessionId;
    status: _BookingStatus;
    junior: Principal;
    subjectCode: string;
    senior: Principal;
    price: bigint;
    dateTime: _Time;
}): {
    id: SessionId;
    status: BookingStatus;
    junior: Principal;
    subjectCode: string;
    senior: Principal;
    price: bigint;
    dateTime: Time;
} {
    return {
        id: value.id,
        status: from_candid_BookingStatus_n23(_uploadFile, _downloadFile, value.status),
        junior: value.junior,
        subjectCode: value.subjectCode,
        senior: value.senior,
        price: value.price,
        dateTime: value.dateTime
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch: string;
    semester: bigint;
    name: string;
    role: _UserRole;
    email: string;
    university: string;
}): {
    branch: string;
    semester: bigint;
    name: string;
    role: UserRole;
    email: string;
    university: string;
} {
    return {
        branch: value.branch,
        semester: value.semester,
        name: value.name,
        role: from_candid_UserRole_n28(_uploadFile, _downloadFile, value.role),
        email: value.email,
        university: value.university
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pdf: null;
} | {
    link: null;
}): FileType {
    return "pdf" in value ? FileType.pdf : "link" in value ? FileType.link : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "pending" in value ? BookingStatus.pending : "completed" in value ? BookingStatus.completed : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    junior: null;
} | {
    senior: null;
}): UserRole {
    return "junior" in value ? UserRole.junior : "senior" in value ? UserRole.senior : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Resource>): Array<Resource> {
    return value.map((x)=>from_candid_Resource_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_TutorProfile>): Array<TutorProfile> {
    return value.map((x)=>from_candid_TutorProfile_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SessionBooking>): Array<SessionBooking> {
    return value.map((x)=>from_candid_SessionBooking_n21(_uploadFile, _downloadFile, x));
}
function to_candid_BookingStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): _BookingStatus {
    return to_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function to_candid_FileType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): _FileType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Resource_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Resource): _Resource {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_SessionBooking_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SessionBooking): _SessionBooking {
    return to_candid_record_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n34(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n36(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ResourceId;
    url: string;
    title: string;
    semester: bigint;
    subjectCode: string;
    fileType: FileType;
    uploader: Principal;
}): {
    id: _ResourceId;
    url: string;
    title: string;
    semester: bigint;
    subjectCode: string;
    fileType: _FileType;
    uploader: Principal;
} {
    return {
        id: value.id,
        url: value.url,
        title: value.title,
        semester: value.semester,
        subjectCode: value.subjectCode,
        fileType: to_candid_FileType_n3(_uploadFile, _downloadFile, value.fileType),
        uploader: value.uploader
    };
}
function to_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    branch: string;
    semester: bigint;
    name: string;
    role: UserRole;
    email: string;
    university: string;
}): {
    branch: string;
    semester: bigint;
    name: string;
    role: _UserRole;
    email: string;
    university: string;
} {
    return {
        branch: value.branch,
        semester: value.semester,
        name: value.name,
        role: to_candid_UserRole_n35(_uploadFile, _downloadFile, value.role),
        email: value.email,
        university: value.university
    };
}
function to_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: SessionId;
    status: BookingStatus;
    junior: Principal;
    subjectCode: string;
    senior: Principal;
    price: bigint;
    dateTime: Time;
}): {
    id: _SessionId;
    status: _BookingStatus;
    junior: Principal;
    subjectCode: string;
    senior: Principal;
    price: bigint;
    dateTime: _Time;
} {
    return {
        id: value.id,
        status: to_candid_BookingStatus_n9(_uploadFile, _downloadFile, value.status),
        junior: value.junior,
        subjectCode: value.subjectCode,
        senior: value.senior,
        price: value.price,
        dateTime: value.dateTime
    };
}
function to_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingStatus): {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == BookingStatus.pending ? {
        pending: null
    } : value == BookingStatus.completed ? {
        completed: null
    } : value == BookingStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    junior: null;
} | {
    senior: null;
} {
    return value == UserRole.junior ? {
        junior: null
    } : value == UserRole.senior ? {
        senior: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileType): {
    pdf: null;
} | {
    link: null;
} {
    return value == FileType.pdf ? {
        pdf: null
    } : value == FileType.link ? {
        link: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
